# Generated by Django 3.1.2 on 2020-10-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
    ]
