# Generated by Django 3.1.2 on 2020-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20201031_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
